// Constants used for redux action types to prevent typos

export const ADD_TOAST = 'ADD_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';
export const TOAST_FADE_IN = 'TOAST_FADE_IN';
export const TOAST_FADE_OUT = 'TOAST_FADE_OUT';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

export const FETCH_MONUMENT_PENDING = 'FETCH_MONUMENT_PENDING';
export const FETCH_MONUMENT_SUCCESS = 'FETCH_MONUMENT_SUCCESS';
export const FETCH_MONUMENT_ERROR = 'FETCH_MONUMENT_ERROR';

export const SEARCH_MONUMENTS_PENDING = 'SEARCH_MONUMENTS_PENDING';
export const SEARCH_MONUMENTS_SUCCESS = 'SEARCH_MONUMENTS_SUCCESS';
export const SEARCH_MONUMENTS_ERROR = 'SEARCH_MONUMENTS_ERROR';

export const FETCH_MAP_MONUMENTS_PENDING = 'FETCH_MAP_MONUMENTS_PENDING';
export const FETCH_MAP_MONUMENTS_SUCCESS = 'FETCH_MAP_MONUMENTS_SUCCESS';
export const FETCH_MAP_MONUMENTS_ERROR = 'FETCH_MAP_MONUMENTS_ERROR';

export const FETCH_NEARBY_MONUMENTS_PENDING = 'FETCH_NEARBY_MONUMENTS_PENDING';
export const FETCH_NEARBY_MONUMENTS_SUCCESS = 'FETCH_NEARBY_MONUMENTS_SUCCESS';
export const FETCH_NEARBY_MONUMENTS_ERROR = 'FETCH_NEARBY_MONUMENTS_ERROR';

export const FETCH_RELATED_MONUMENTS_PENDING = 'FETCH_RELATED_MONUMENTS_PENDING';
export const FETCH_RELATED_MONUMENTS_SUCCESS = 'FETCH_RELATED_MONUMENTS_SUCCESS';
export const FETCH_RELATED_MONUMENTS_ERROR = 'FETCH_RELATED_MONUMENTS_ERROR';

export const TAGS_SEARCH_PENDING = 'TAGS_SEARCH_PENDING';
export const TAGS_SEARCH_SUCCESS = 'TAGS_SEARCH_SUCCESS';
export const TAGS_SEARCH_ERROR = 'TAGS_SEARCH_ERROR';
export const TAGS_LOAD_PENDING = 'TAGS_LOAD_PENDING';
export const TAGS_LOAD_SUCCESS = 'TAGS_LOAD_SUCCESS';
export const TAGS_LOAD_ERROR = 'TAGS_LOAD_ERROR';
export const MATERIALS_SEARCH_PENDING = 'MATERIALS_SEARCH_PENDING';
export const MATERIALS_SEARCH_SUCCESS = 'MATERIALS_SEARCH_SUCCESS';
export const MATERIALS_SEARCH_ERROR = 'MATERIALS_SEARCH_ERROR';
export const MATERIALS_LOAD_PENDING = 'MATERIALS_LOAD_PENDING';
export const MATERIALS_LOAD_SUCCESS = 'MATERIALS_LOAD_SUCCESS';
export const MATERIALS_LOAD_ERROR = 'MATERIALS_LOAD_ERROR';

export const CREATE_MONUMENT_PENDING = 'CREATE_MONUMENT_PENDING';
export const CREATE_MONUMENT_SUCCESS = 'CREATE_MONUMENT_SUCCESS';
export const CREATE_MONUMENT_ERROR = 'CREATE_MONUMENT_ERROR';

export const TAG_DIRECTORY_FETCH_TAGS_PENDING = 'TAG_DIRECTORY_FETCH_TAGS_PENDING';
export const TAG_DIRECTORY_FETCH_TAGS_SUCCESS = 'TAG_DIRECTORY_FETCH_TAGS_SUCCESS';
export const TAG_DIRECTORY_FETCH_TAGS_ERROR = 'TAG_DIRECTORY_FETCH_TAGS_ERROR';

export const BULK_VALIDATE_MONUMENTS_PENDING = 'BULK_VALIDATE_MONUMENTS_PENDING';
export const BULK_VALIDATE_MONUMENTS_SUCCESS = 'BULK_VALIDATE_MONUMENTS_SUCCESS';
export const BULK_VALIDATE_MONUMENTS_ERROR = 'BULK_VALIDATE_MONUMENTS_ERROR';

export const BULK_CREATE_MONUMENTS_SUCCESS = 'BULK_CREATE_MONUMENTS_SUCCESS';
export const BULK_CREATE_MONUMENTS_PENDING = 'BULK_CREATE_MONUMENTS_PENDING';
export const BULK_CREATE_MONUMENTS_ERROR = 'BULK_CREATE_MONUMENTS_ERROR';

export const ABOUT_PAGE_FETCH_CONTRIBUTORS_PENDING = 'ABOUT_PAGE_FETCH_CONTRIBUTORS_PENDING';
export const ABOUT_PAGE_FETCH_CONTRIBUTORS_SUCCESS = 'ABOUT_PAGE_FETCH_CONTRIBUTORS_SUCCESS';
export const ABOUT_PAGE_FETCH_CONTRIBUTORS_ERROR = 'ABOUT_PAGE_FETCH_CONTRIBUTORS_ERROR';
export const ABOUT_PAGE_FETCH_MONUMENT_STATISTICS_PENDING = 'ABOUT_PAGE_FETCH_MONUMENT_STATISTICS_PENDING';
export const ABOUT_PAGE_FETCH_MONUMENT_STATISTICS_SUCCESS = 'ABOUT_PAGE_FETCH_MONUMENT_STATISTICS_SUCCESS';
export const ABOUT_PAGE_FETCH_MONUMENT_STATISTICS_ERROR = 'ABOUT_PAGE_FETCH_MONUMENT_STATISTICS_ERROR';

export const FETCH_MONUMENT_UPDATE_PENDING = 'FETCH_MONUMENT_UPDATE_PENDING';
export const FETCH_MONUMENT_UPDATE_SUCCESS = 'FETCH_MONUMENT_UPDATE_SUCCESS';
export const FETCH_MONUMENT_UPDATE_ERROR = 'FETCH_MONUMENT_UPDATE_ERROR';

export const UPDATE_MONUMENT_PENDING = 'UPDATE_MONUMENT_PENDING';
export const UPDATE_MONUMENT_SUCCESS = 'UPDATE_MONUMENT_SUCCESS';
export const UPDATE_MONUMENT_ERROR = 'UPDATE_MONUMENT_ERROR';