// Constants used for redux action types to prevent typos

export const ADD_TOAST = 'ADD_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';
export const TOAST_FADE_IN = 'TOAST_FADE_IN';
export const TOAST_FADE_OUT = 'TOAST_FADE_OUT';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

export const FETCH_MONUMENT_PENDING = 'FETCH_MONUMENT_PENDING';
export const FETCH_MONUMENT_SUCCESS = 'FETCH_MONUMENT_SUCCESS';
export const FETCH_MONUMENT_ERROR = 'FETCH_MONUMENT_ERROR';

export const SEARCH_MONUMENTS_PENDING = 'SEARCH_MONUMENTS_PENDING';
export const SEARCH_MONUMENTS_SUCCESS = 'SEARCH_MONUMENTS_SUCCESS';
export const SEARCH_MONUMENTS_ERROR = 'SEARCH_MONUMENTS_ERROR';

export const FETCH_MAP_MONUMENTS_PENDING = 'FETCH_MAP_MONUMENTS_PENDING';
export const FETCH_MAP_MONUMENTS_SUCCESS = 'FETCH_MAP_MONUMENTS_SUCCESS';
export const FETCH_MAP_MONUMENTS_ERROR = 'FETCH_MAP_MONUMENTS_ERROR';

export const FETCH_NEARBY_MONUMENTS_PENDING = 'FETCH_NEARBY_MONUMENTS_PENDING';
export const FETCH_NEARBY_MONUMENTS_SUCCESS = 'FETCH_NEARBY_MONUMENTS_SUCCESS';
export const FETCH_NEARBY_MONUMENTS_ERROR = 'FETCH_NEARBY_MONUMENTS_ERROR';

export const FETCH_RELATED_MONUMENTS_PENDING = 'FETCH_RELATED_MONUMENTS_PENDING';
export const FETCH_RELATED_MONUMENTS_SUCCESS = 'FETCH_RELATED_MONUMENTS_SUCCESS';
export const FETCH_RELATED_MONUMENTS_ERROR = 'FETCH_RELATED_MONUMENTS_ERROR';

export const FETCH_FAVORITE_PENDING = 'FETCH_FAVORITE_PENDING';
export const FETCH_FAVORITE_SUCCESS = 'FETCH_FAVORITE_SUCCESS';
export const FETCH_FAVORITE_ERROR = 'FETCH_FAVORITE_ERROR';
export const CREATE_FAVORITE_PENDING = 'CREATE_FAVORITE_PENDING';
export const CREATE_FAVORITE_SUCCESS = 'CREATE_FAVORITE_SUCCESS';
export const CREATE_FAVORITE_ERROR = 'CREATE_FAVORITE_ERROR';
export const DELETE_FAVORITE_PENDING = 'DELETE_FAVORITE_PENDING';
export const DELETE_FAVORITE_SUCCESS = 'DELETE_FAVORITE_SUCCESS';
export const DELETE_FAVORITE_ERROR = 'DELETE_FAVORITE_ERROR';

export const TAGS_SEARCH_PENDING = 'TAGS_SEARCH_PENDING';
export const TAGS_SEARCH_SUCCESS = 'TAGS_SEARCH_SUCCESS';
export const TAGS_SEARCH_ERROR = 'TAGS_SEARCH_ERROR';
export const TAGS_LOAD_PENDING = 'TAGS_LOAD_PENDING';
export const TAGS_LOAD_SUCCESS = 'TAGS_LOAD_SUCCESS';
export const TAGS_LOAD_ERROR = 'TAGS_LOAD_ERROR';
export const MATERIALS_SEARCH_PENDING = 'MATERIALS_SEARCH_PENDING';
export const MATERIALS_SEARCH_SUCCESS = 'MATERIALS_SEARCH_SUCCESS';
export const MATERIALS_SEARCH_ERROR = 'MATERIALS_SEARCH_ERROR';
export const MATERIALS_LOAD_PENDING = 'MATERIALS_LOAD_PENDING';
export const MATERIALS_LOAD_SUCCESS = 'MATERIALS_LOAD_SUCCESS';
export const MATERIALS_LOAD_ERROR = 'MATERIALS_LOAD_ERROR';

export const CREATE_MONUMENT_PENDING = 'CREATE_MONUMENT_PENDING';
export const CREATE_MONUMENT_SUCCESS = 'CREATE_MONUMENT_SUCCESS';
export const CREATE_MONUMENT_ERROR = 'CREATE_MONUMENT_ERROR';

export const TAG_DIRECTORY_FETCH_TAGS_PENDING = 'TAG_DIRECTORY_FETCH_TAGS_PENDING';
export const TAG_DIRECTORY_FETCH_TAGS_SUCCESS = 'TAG_DIRECTORY_FETCH_TAGS_SUCCESS';
export const TAG_DIRECTORY_FETCH_TAGS_ERROR = 'TAG_DIRECTORY_FETCH_TAGS_ERROR';

export const BULK_VALIDATE_MONUMENTS_PENDING = 'BULK_VALIDATE_MONUMENTS_PENDING';
export const BULK_VALIDATE_MONUMENTS_SUCCESS = 'BULK_VALIDATE_MONUMENTS_SUCCESS';
export const BULK_VALIDATE_MONUMENTS_ERROR = 'BULK_VALIDATE_MONUMENTS_ERROR';

export const BULK_CREATE_MONUMENTS_SUCCESS = 'BULK_CREATE_MONUMENTS_SUCCESS';
export const BULK_CREATE_MONUMENTS_PENDING = 'BULK_CREATE_MONUMENTS_PENDING';
export const BULK_CREATE_MONUMENTS_ERROR = 'BULK_CREATE_MONUMENTS_ERROR';

export const ABOUT_PAGE_FETCH_CONTRIBUTORS_PENDING = 'ABOUT_PAGE_FETCH_CONTRIBUTORS_PENDING';
export const ABOUT_PAGE_FETCH_CONTRIBUTORS_SUCCESS = 'ABOUT_PAGE_FETCH_CONTRIBUTORS_SUCCESS';
export const ABOUT_PAGE_FETCH_CONTRIBUTORS_ERROR = 'ABOUT_PAGE_FETCH_CONTRIBUTORS_ERROR';
export const ABOUT_PAGE_FETCH_MONUMENT_STATISTICS_PENDING = 'ABOUT_PAGE_FETCH_MONUMENT_STATISTICS_PENDING';
export const ABOUT_PAGE_FETCH_MONUMENT_STATISTICS_SUCCESS = 'ABOUT_PAGE_FETCH_MONUMENT_STATISTICS_SUCCESS';
export const ABOUT_PAGE_FETCH_MONUMENT_STATISTICS_ERROR = 'ABOUT_PAGE_FETCH_MONUMENT_STATISTICS_ERROR';

export const SIGNUP_PENDING = 'SIGNUP_PENDING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CREATE_SESSION = 'CREATE_SESSION';
export const CLEAR_SESSION = 'CLEAR_SESSION';
export const CONFIRM_SIGNUP_PENDING = 'CONFIRM_SIGNUP_PENDING';
export const CONFIRM_SIGNUP_SUCCESS = 'CONFIRM_SIGNUP_SUCCESS';
export const CONFIRM_SIGNUP_ERROR = 'CONFIRM_SIGNUP_ERROR';
export const RESEND_CONFIRMATION_PENDING = 'RESEND_CONFIRMATION_PENDING';
export const RESEND_CONFIRMATION_SUCCESS = 'RESEND_CONFIRMATION_SUCCESS';
export const RESEND_CONFIRMATION_ERROR = 'RESEND_CONFIRMATION_ERROR';
export const BEGIN_PASSWORD_RESET_PENDING = 'BEGIN_PASSWORD_RESET_PENDING';
export const BEGIN_PASSWORD_RESET_SUCCESS = 'BEGIN_PASSWORD_RESET_SUCCESS';
export const BEGIN_PASSWORD_RESET_ERROR = 'BEGIN_PASSWORD_RESET_ERROR';
export const FINISH_PASSWORD_RESET_PENDING = 'FINISH_PASSWORD_RESET_PENDING';
export const FINISH_PASSWORD_RESET_SUCCESS = 'FINISH_PASSWORD_RESET_SUCCESS';
export const FINISH_PASSWORD_RESET_ERROR = 'FINISH_PASSWORD_RESET_ERROR';
export const FETCH_FAVORITES_PENDING = 'FETCH_FAVORITES_PENDING';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const FETCH_FAVORITES_ERROR = 'FETCH_FAVORITES_ERROR';

export const FETCH_MONUMENT_UPDATE_PENDING = 'FETCH_MONUMENT_UPDATE_PENDING';
export const FETCH_MONUMENT_UPDATE_SUCCESS = 'FETCH_MONUMENT_UPDATE_SUCCESS';
export const FETCH_MONUMENT_UPDATE_ERROR = 'FETCH_MONUMENT_UPDATE_ERROR';

export const UPDATE_MONUMENT_PENDING = 'UPDATE_MONUMENT_PENDING';
export const UPDATE_MONUMENT_SUCCESS = 'UPDATE_MONUMENT_SUCCESS';
export const UPDATE_MONUMENT_ERROR = 'UPDATE_MONUMENT_ERROR';

export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET';
export const UPDATE_EMAIL_PENDING = 'UPDATE_EMAIL_PENDING';
export const UPDATE_EMAIL_SUCCESS = 'UPDATE_EMAIL_SUCCESS';
export const UPDATE_EMAIL_ERROR = 'UPDATE_EMAIL_ERROR';

export const FETCH_DUPLICATES_PENDING = 'FETCH_DUPLICATES_PENDING';
export const FETCH_DUPLICATES_SUCCESS = 'FETCH_DUPLICATES_SUCCESS';
export const FETCH_DUPLICATES_ERROR = 'FETCH_DUPLICATES_ERROR';