// Constants used for redux action types to prevent typos

export const ADD_TOAST = 'ADD_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';
export const TOAST_FADE_IN = 'TOAST_FADE_IN';
export const TOAST_FADE_OUT = 'TOAST_FADE_OUT';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

export const FETCH_MONUMENT_PENDING = 'FETCH_MONUMENT_PENDING';
export const FETCH_MONUMENT_SUCCESS = 'FETCH_MONUMENT_SUCCESS';
export const FETCH_MONUMENT_ERROR = 'FETCH_MONUMENT_ERROR';

export const SEARCH_MONUMENTS_PENDING = 'SEARCH_MONUMENTS_PENDING';
export const SEARCH_MONUMENTS_SUCCESS = 'SEARCH_MONUMENTS_SUCCESS';
export const SEARCH_MONUMENTS_ERROR = 'SEARCH_MONUMENTS_ERROR';

export const FETCH_MAP_MONUMENTS_PENDING = 'FETCH_MAP_MONUMENTS_PENDING';
export const FETCH_MAP_MONUMENTS_SUCCESS = 'FETCH_MAP_MONUMENTS_SUCCESS';
export const FETCH_MAP_MONUMENTS_ERROR = 'FETCH_MAP_MONUMENTS_ERROR';

export const FETCH_NEARBY_MONUMENTS_PENDING = 'FETCH_NEARBY_MONUMENTS_PENDING';
export const FETCH_NEARBY_MONUMENTS_SUCCESS = 'FETCH_NEARBY_MONUMENTS_SUCCESS';
export const FETCH_NEARBY_MONUMENTS_ERROR = 'FETCH_NEARBY_MONUMENTS_ERROR';

export const FETCH_RELATED_MONUMENTS_PENDING = 'FETCH_RELATED_MONUMENTS_PENDING';
export const FETCH_RELATED_MONUMENTS_SUCCESS = 'FETCH_RELATED_MONUMENTS_SUCCESS';
export const FETCH_RELATED_MONUMENTS_ERROR = 'FETCH_RELATED_MONUMENTS_ERROR';

export const FILTER_TAGS_SEARCH_PENDING = 'FILTER_TAGS_SEARCH_PENDING';
export const FILTER_TAGS_SEARCH_SUCCESS = 'FILTER_TAGS_SEARCH_SUCCESS';
export const FILTER_TAGS_SEARCH_ERROR = 'FILTER_TAGS_SEARCH_ERROR';
export const FILTER_TAGS_LOAD_PENDING = 'FILTER_TAGS_LOAD_PENDING';
export const FILTER_TAGS_LOAD_SUCCESS = 'FILTER_TAGS_LOAD_SUCCESS';
export const FILTER_TAGS_LOAD_ERROR = 'FILTER_TAGS_LOAD_ERROR';
export const FILTER_MATERIALS_SEARCH_PENDING = 'FILTER_MATERIALS_SEARCH_PENDING';
export const FILTER_MATERIALS_SEARCH_SUCCESS = 'FILTER_MATERIALS_SEARCH_SUCCESS';
export const FILTER_MATERIALS_SEARCH_ERROR = 'FILTER_MATERIALS_SEARCH_ERROR';
export const FILTER_MATERIALS_LOAD_PENDING = 'FILTER_MATERIALS_LOAD_PENDING';
export const FILTER_MATERIALS_LOAD_SUCCESS = 'FILTER_MATERIALS_LOAD_SUCCESS';
export const FILTER_MATERIALS_LOAD_ERROR = 'FILTER_MATERIALS_LOAD_ERROR';
