language: java
install: true
os: linux
dist: trusty
jdk: openjdk12
script:
- "./gradlew build -s"
before_install:
- openssl aes-256-cbc -K $encrypted_0fbd74be76e8_key -iv $encrypted_0fbd74be76e8_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
after_success:
  - .travis/deploy.sh