#!/bin/bash

# This is the git hook that builds and restarts the server service on the VM after a deploy is made.
# This file is not used anywhere, the real version lives in .git/hooks, this version is only for reference and versioning

# This script runs gradle locally after a deploy is made so that the server runs the newest version
cd ..
pwd
./gradlew copyWebApp -s
./gradlew build -s
echo CLEANUP
unset GIT_DIR
git --work-tree=. stash save --keep-index && git --work-tree=. stash drop
echo SERVER: Restarting server process...
sudo systemctl stop monumental
sudo systemctl start monumental