# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Staging Deploy

on:
  push:
    branches: [ "staging" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_STAGING_HOST }}
          username: ${{ secrets.AWS_STAGING_USER }}
          key: ${{ secrets.AWS_STAGING_KEY }}
          script: echo test
